version: '3.8'

services:
  app:
    build: .
    container_name: transflow-app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy 
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - transflow-network

  
  mongo:
    image: mongo:latest
    container_name: transflow-mongo
    ports:
      - "27017:27017"
    networks:
      - transflow-network

 
  redis:
    image: redis:latest
    container_name: transflow-redis
    ports:
      - "6379:6379"
    networks:
      - transflow-network

 
  rabbitmq:
    image: rabbitmq:3-management
    container_name: transflow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - transflow-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

networks:
  transflow-network:
    driver: bridge